using ChatCRM.Application.Billing.DTOs;

namespace ChatCRM.Application.Interfaces
{
    /// <summary>
    /// Issues monthly billing statements. Invoices are not auto-generated by a cron in v1 —
    /// the user clicks "Generate" on the page and the row is snapshotted at that point.
    /// Numbering scheme: <c>INV-{YYYY}{MM}-{SEQ:D4}</c>, where <c>SEQ</c> resets per workspace
    /// per month.
    /// </summary>
    public interface IInvoiceService
    {
        /// <summary>List all invoices for the workspace, newest first.</summary>
        Task<List<InvoiceListItemDto>> ListAsync(CancellationToken cancellationToken = default);

        /// <summary>Snapshot totals for a single invoice (read-only).</summary>
        Task<InvoiceDetailDto?> GetAsync(int id, CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate (or regenerate) the invoice for the calendar month containing <paramref name="anyDayInPeriod"/>.
        /// If a Draft invoice already exists for that period it is updated in place; an Issued
        /// invoice is locked and re-call returns the existing row unchanged.
        /// </summary>
        Task<InvoiceDetailDto> GenerateForMonthAsync(
            DateTime anyDayInPeriod, string actingUserId, CancellationToken cancellationToken = default);

        /// <summary>Mark a Draft invoice as Issued (immutable from this point — like a Stripe finalised invoice).</summary>
        Task<InvoiceDetailDto> IssueAsync(int id, string actingUserId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Render the invoice PDF on the fly. Bytes are NOT persisted — re-rendering a year
        /// later under a newer renderer is fine because all the data lives on the row.
        /// </summary>
        Task<byte[]> RenderPdfAsync(int id, CancellationToken cancellationToken = default);
    }
}
