namespace ChatCRM.Domain.Entities
{
    public enum MessageDirection : byte
    {
        Incoming = 0,
        Outgoing = 1,
        /// <summary>Internal team note — not sent to WhatsApp, visible only to agents.</summary>
        Note = 2
    }

    public enum MessageStatus : byte
    {
        Sent = 0,
        Delivered = 1,
        Read = 2
    }

    public enum MessageKind : byte
    {
        Text = 0,
        Image = 1,
        Video = 2,
        Audio = 3,
        Document = 4,
        Sticker = 5
    }

    /// <summary>Speech-to-text lifecycle for an audio/voice message.</summary>
    public enum TranscriptionStatus : byte
    {
        /// <summary>Not an audio message, or transcription was never requested.</summary>
        None = 0,
        /// <summary>Queued — waiting for the background worker to pick it up.</summary>
        Pending = 1,
        /// <summary>A worker is currently calling the speech-to-text provider.</summary>
        Processing = 2,
        /// <summary>Transcribed successfully — text is in <see cref="Message.TranscriptionText"/>.</summary>
        Done = 3,
        /// <summary>Permanently failed after exhausting retries.</summary>
        Failed = 4
    }

    public class Message
    {
        public int Id { get; set; }

        public int ConversationId { get; set; }
        public Conversation Conversation { get; set; } = null!;

        public string Body { get; set; } = string.Empty;

        public MessageDirection Direction { get; set; }

        public MessageStatus Status { get; set; } = MessageStatus.Sent;

        public MessageKind Kind { get; set; } = MessageKind.Text;

        /// <summary>Public URL (under /media/...) of the attached file when Kind != Text.</summary>
        public string? MediaUrl { get; set; }

        /// <summary>MIME type of the attached file, e.g. "image/jpeg".</summary>
        public string? MediaMimeType { get; set; }

        /// <summary>Original filename (only meaningful for documents).</summary>
        public string? MediaFileName { get; set; }

        /// <summary>
        /// Evolution API message ID — used to deduplicate webhook deliveries.
        /// </summary>
        public string? ExternalId { get; set; }

        public DateTime SentAt { get; set; } = DateTime.UtcNow;

        /// <summary>Set when the contact edits the message on WhatsApp; null otherwise.</summary>
        public DateTime? EditedAt { get; set; }

        /// <summary>True when the contact revokes ("delete for everyone") the message on WhatsApp.</summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Author user ID for internal notes (null for incoming/outgoing chat messages).
        /// </summary>
        public string? AuthorUserId { get; set; }
        public User? AuthorUser { get; set; }

        /// <summary>
        /// Set when this outgoing message was generated by an AI agent rather than typed by a
        /// human (in which case <see cref="AuthorUserId"/> is null). Lets the UI badge the bubble
        /// and lets audit/billing distinguish human-authored vs AI-authored sends.
        /// </summary>
        public int? AuthorAgentId { get; set; }
        public Agent? AuthorAgent { get; set; }

        // ── Speech-to-text (audio messages) ───────────────────────────────
        // Populated by the background TranscriptionWorker for Kind == Audio messages. The text
        // is read-only inspection data and the input the AI pipeline can consume.

        public TranscriptionStatus TranscriptionStatus { get; set; } = TranscriptionStatus.None;

        /// <summary>The transcribed text once <see cref="TranscriptionStatus"/> is Done.</summary>
        public string? TranscriptionText { get; set; }

        /// <summary>Detected (or requested) language code, e.g. "en", "ar".</summary>
        public string? TranscriptionLanguage { get; set; }

        /// <summary>Which provider produced the text, e.g. "groq", "whisper-api", "local", "mock".</summary>
        public string? TranscriptionProvider { get; set; }

        /// <summary>How many transcription attempts have been made (drives retry/backoff).</summary>
        public int TranscriptionAttemptCount { get; set; }

        /// <summary>Last provider error message, kept for inspection when status is Failed.</summary>
        public string? TranscriptionError { get; set; }

        /// <summary>Earliest UTC time the worker may retry after a transient failure (backoff).</summary>
        public DateTime? TranscriptionNextAttemptUtc { get; set; }
    }
}
